2020/djangoblog/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts';


urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

2020/djangoblog/articles/urls.py
from django.urls import path
from articles.views import articlesView
from . import views
app_name = 'articles'
urlpatterns = [
    path('', articlesView.as_view(), name='article_list'),
    # path(r'^(P?<slug>[\w-]+)/$', editArticlesView.as_view(), name='details'),
    path('create', views.article_create, name='create'),
    path('<slug:slug>', views.article_details, name='details'),
]

2020/djangoblog/djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from djangoblog.views import MyView, indexView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns;
from django.conf.urls.static import static
from django.conf import settings
# from articles import views as article_views
from articles.views import articlesView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/',  MyView.as_view(), name='about'),
    path('articles/',   include('articles.urls')),
    path('accounts/',   include('accounts.urls')),
    path('', articlesView.as_view(), name='index'),
]

urlpatterns += staticfiles_urlpatterns();
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2020/djangoblog/accounts/models.py
from django.db import models

# Create your models here.

2020/djangoblog/articles/models.py
from django.db import models
from django.contrib.auth.models import User;

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100);
    slug = models.SlugField();
    body = models.TextField();
    date = models.DateTimeField(auto_now_add=True);
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.DO_NOTHING)


    def __str__(self):
         return self.title

    def snippet(self):
        return self.body[:50] + '...';

2020/djangoblog/articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    
    class Meta:
        model = models.Article
        fields = ["title","slug", "body", "thumb"];

2020/djangoblog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save();
            login(request, user);
            return redirect('articles:article_list')
    # return render('templa')
    else:
      form = UserCreationForm;
    return render(request, 'accounts/signup.html', {'form':form})
def login_view(request):
  if request.method == 'POST':
      form = AuthenticationForm(data=request.POST);
      if form.is_valid():
        user = form.get_user();
        login(request, user);
        if 'next' in request.POST:
          return redirect(request.POST.get('next'))
        else:
          return redirect('articles:article_list')

  else:
    form = AuthenticationForm();
  return render(request, 'accounts/login.html', {'form':form})


def logout_view(request):
    if request.method =='POST':
      logout(request);
      return redirect('articles:article_list')

2020/djangoblog/articles/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Article;
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms


# Create your views here.
class articlesView(View):
    def get(self, request, *args, **kwargs):
        articles = Article.objects.all().order_by("date");
        # return HttpResponse("its index page");
        return render(request, 'articles/article_list.html', {'articles':articles})
# class editArticlesView(View):
#     def get(self, request, slg, *args, **kwargs):
#         article = Article.objects.get(slug=slg)
#         print(article)
        # return HttpResponse("its index page");
        # return render(request, 'articles/article_details.html', {'article':article});
def article_details(request, slug):
     article = Article.objects.get(slug=slug)
     print(article.body)
        # return HttpResponse("its index page");
     return render(request, 'articles/article_details.html', {'article':article});

@login_required(login_url="/accounts/login/")
def article_create(request):
        if request.method == 'POST':
                form = forms.CreateArticle(request.POST, request.FILES);
                if form.is_valid():
                        instance = form.save(commit=False)
                        instance.author = request.user
                        instance.save();
                        return redirect('articles:article_list')
        else:
                form = forms.CreateArticle();
                return render(request, 'articles/article_create.html', {'form':form})

2020/djangoblog/djangoblog/views.py
from django.http import HttpResponse
from django.views import View
from django.shortcuts import render


class MyView(View):
    def get(self, request, *args, **kwargs):
        # return HttpResponse("hello world");
        return render(request, 'about.html')

class indexView(View):
    def get(self, request, *args, **kwargs):
        # return HttpResponse("its index page");
        return render(request, 'homepage.html')

2020/djangoblog/accounts/templates/accounts/login.html
{% extends 'layout.html' %}


{% block content %}
<h1>Sign UP</h1>

<form class="site-form" action="{% url 'accounts:login'%}" method="POST">
    {% csrf_token %}
    {{form}}

    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" value="Login">
</form>
{% endblock %}

2020/djangoblog/accounts/templates/accounts/signup.html
{% extends 'layout.html' %}


{% block content %}
<h1>Sign UP</h1>

<form class="site-form" action="/accounts/signup/" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="SignUp">
</form>
{% endblock %}

2020/djangoblog/articles/templates/articles/article_create.html
{% extends 'layout.html' %}


{% block content %}
<div class="create-article">
    <h1>Create An Awesome Article</h1>
    <form action="{% url 'articles:create' %}" class="site-form"ethod="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Create">
    </form>
</div>
{% endblock %}

2020/djangoblog/articles/templates/articles/article_details.html
{% extends 'layout.html' %}


{% block content %}
<!-- <h1>{{article.slug}}</h1> -->

<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" alt="thumbnail">
        <h1>{{article.title}}</h1>
        <p>{{article.body}}</p>
        <p>{{article.date}}</p>
    </div>
</div>
{% endblock %}

2020/djangoblog/articles/templates/articles/article_list.html
{% extends 'layout.html'%}

{% block content %}
    <h1>Article List</h1><hr>
    <div class="article">
        {% for article in articles %}
        <div class="article">
            <h1><a href="{% url 'articles:details' slug=article.slug %}">{{article.title}}</a></h1>
            <p>{{article.snippet}}</p>
            <p>{{article.date}}</p>
        </div>
        {%endfor%}
    </div>
{% endblock %}

2020/djangoblog/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About page</title>
</head>
<body>
    <h1>Welcome to About page</h1>
    <p>this is about page</p>
</body>
</html>

2020/djangoblog/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home page</title>
</head>
<body>
    <h1>Welcome to home page</h1>
    <p>this is home page</p>
</body>
</html>

2020/djangoblog/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<div class="wrapper">
    <h1><a href="{% url 'index' %}"><img src="{% static 'logo.png' %}" /></a></h1>
    <nav>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <form action="{% url 'accounts:logout' %}" method="POST" class="logout-link">
                    {% csrf_token%}
                    <button type="submit">Logout</button>
                </form>
            </li>
            <li><a href="{% url 'articles:create' %}">Create Article</a></li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}" class="highlight">Login</a></li>
            <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
            {% endif %}
        </ul>
    </nav>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>